name: qgis-test-action
on: workflow_dispatch
jobs:
  test-package:
    runs-on: ubuntu-20.04
    steps:
      - run: apt-get install python3-qgis
      - run: python3 -c "from qgis import core; print(core.__name__)"
